In [4]:
import pandas as pd

# Age of Vaccination Nationwide per 100K rate

In [5]:
age_df=pd.read_csv("Resources/cases_by_age_vac_status.csv")
age_df.tail(10)

,date,agegroup,cases_unvac_rate_per100K,cases_partial_vac_rate_per100K,cases_notfull_vac_rate_per100K,cases_full_vac_rate_per100K,cases_boost_vac_rate_per100K,cases_unvac_rate_7ma,cases_partial_vac_rate_7ma,cases_notfull_vac_rate_7ma,cases_full_vac_rate_7ma,cases_boost_vac_rate_7ma
1018,2022-06-22,5-11yrs,NaN,NaN,1.40,2.54,0.00,NaN,NaN,0.86,2.14,-0.00
1019,2022-06-22,60+,NaN,NaN,30.50,4.64,7.04,NaN,NaN,23.23,3.95,5.82
1020,2022-06-22,ALL,NaN,NaN,2.68,2.20,7.54,NaN,NaN,2.69,2.14,5.87
1021,2022-06-23,0-4yrs,NaN,NaN,3.73,0.00,0.00,NaN,NaN,2.80,0.00,0.00
1022,2022-06-23,12-17yrs,NaN,NaN,0.00,1.29,2.79,NaN,NaN,0.62,1.01,2.32
1023,2022-06-23,18-39yrs,NaN,NaN,4.20,2.39,8.93,NaN,NaN,3.02,1.95,6.70
1024,2022-06-23,40-59yrs,NaN,NaN,0.92,3.21,8.42,NaN,NaN,2.47,2.17,5.82
1025,2022-06-23,5-11yrs,NaN,NaN,1.55,1.38,0.00,NaN,NaN,0.95,1.81,-0.00
1026,2022-06-23,60+,NaN,NaN,21.91,5.03,8.69,NaN,NaN,23.35,4.17,6.18
1027,2022-06-23,ALL,NaN,NaN,3.09,2.65,8.53,NaN,NaN,2.76,2.11,6.11

In [6]:
age_df["agegroup"].unique()
age_df.columns

Index(['date', 'agegroup', 'cases_unvac_rate_per100K',
       'cases_partial_vac_rate_per100K', 'cases_notfull_vac_rate_per100K',
       'cases_full_vac_rate_per100K', 'cases_boost_vac_rate_per100K',
       'cases_unvac_rate_7ma', 'cases_partial_vac_rate_7ma',
       'cases_notfull_vac_rate_7ma', 'cases_full_vac_rate_7ma',
       'cases_boost_vac_rate_7ma'],
      dtype='object')

In [7]:
data_grouped = age_df.groupby("agegroup")[["cases_unvac_rate_per100K", "cases_partial_vac_rate_per100K", 
                                           "cases_notfull_vac_rate_per100K", "cases_full_vac_rate_per100K", 
                                           "cases_boost_vac_rate_per100K", "cases_unvac_rate_7ma", 
                                           "cases_partial_vac_rate_7ma", "cases_notfull_vac_rate_7ma", 
                                           "cases_full_vac_rate_7ma", "cases_boost_vac_rate_7ma"]].mean()
data_grouped 

#I used mean because its a rate per 100k people

,cases_unvac_rate_per100K,cases_partial_vac_rate_per100K,cases_notfull_vac_rate_per100K,cases_full_vac_rate_per100K,cases_boost_vac_rate_per100K,cases_unvac_rate_7ma,cases_partial_vac_rate_7ma,cases_notfull_vac_rate_7ma,cases_full_vac_rate_7ma,cases_boost_vac_rate_7ma
agegroup,,,,,,,,,,
0-11yrs,5.449048,2.337619,NaN,0.216429,NaN,5.519167,2.286667,NaN,0.252778,NaN
0-4yrs,NaN,NaN,7.642571,0.000000,0.000000,NaN,NaN,7.800808,0.000000,0.000000
12-17yrs,13.160714,4.017619,5.187619,4.522993,7.332762,13.378611,4.031667,5.370505,4.583704,7.367677
18-39yrs,11.600476,4.416905,8.168476,6.886122,19.274667,11.640000,4.297778,8.323939,7.115481,19.680909
40-59yrs,10.614048,4.231905,7.398286,7.186531,16.968762,10.690278,4.158056,7.565253,7.474667,17.364343
5-11yrs,NaN,NaN,5.104000,8.022095,31.218095,NaN,NaN,5.175253,8.024747,33.110707
60+,11.690000,0.000000,44.402190,10.321038,13.240000,11.690000,0.000000,45.663939,10.570500,13.661616
60-79yrs,13.620000,2.425366,NaN,1.056829,NaN,14.158286,2.557429,NaN,1.102857,NaN
80+,84.689512,1.563659,NaN,1.077805,NaN,66.971714,1.487714,NaN,1.146857,NaN
ALL,8.652619,4.002619,8.167238,6.652109,15.849429,8.739444,3.945556,8.344747,6.886074,16.250606

In [12]:
unvac_casesfor80plus = age_df.loc[age_df["agegroup"]=="80+", "cases_unvac_rate_per100K"]
unvac_casesfor80plus

5       13.64
12      13.76
19       5.56
26      16.84
33       0.00
40       8.60
47      11.56
54       8.73
61       8.81
68       5.95
75      24.08
82      63.69
89      22.08
96      45.57
103     23.39
110     24.26
117     25.41
124     26.61
131     41.92
138     44.07
145     76.76
152    111.60
159     66.97
166     17.73
173      0.00
180     61.19
187    131.80
194     70.24
201    124.60
208     53.62
215     89.18
222    164.60
229     36.35
236    207.30
243    231.80
250      0.00
257      0.00
264    224.20
271    388.70
278    447.80
285    533.30
Name: cases_unvac_rate_per100K, dtype: float64

Dictionary:
    
cases_unvac_rate_per100K	The case rate per 100,000 for those unvaccinated. Calculated by dividing the number of cases among unvaccinated individuals by the total number of unvaccinated individuals. This rate is provided for the overall population as well as for each age group. 
cases_partial_vac_rate_per100K	The case rate per 100,000 for those partially vaccinated. Calculated by dividing the number of cases among partially vaccinated individuals by the total number of partially vaccinated individuals. This rate is provided for the overall population as well as for each age group. 
cases_notfull_vac_rate_per100K	The case rate per 100,000 for those not fully vaccinated. Calculated by dividing the number of cases among individuals not fully vaccinated by the total number of individuals not fully vaccinated. This rate is calculated for the overall population as well as for each age group.  
cases_full_vac_rate_per100K	The case rate per 100,000 for those fully vaccinated. Calculated by dividing the number of cases among fully vaccinated individuals by the total number of fully vaccinated individuals. This rate is provided for the overall population as well as for each age group. 
cases_boost_vac_rate_per100K	The case rate per 100,000 for those with at least one booster. Calculated by dividing the number of cases among individuals with at least one booster by the total number of individuals with at least one booster. This rate is provided for the overall population as well as for each age group. 
cases_unvac_rate_7ma	The average of the last seven days of the case rate per 100,000 for those unvaccinated
cases_partial_vac_rate_7ma	The average of the last seven days of the case rate per 100,000 for those partially vaccinated
cases_notfull_vac_rate_7ma	The average of the last seven days of the case rate per 100,000 for those not fully vaccinated
cases_full_vac_rate_7ma	The average of the last seven days of the case rate per 100,000 for those fully vaccinated
cases_boost_vac_rate_7ma	The average of the last seven days of the case reate per 100,000 for those with at least one booster

 # Vaccination Nationwide: absolute numbers

In [6]:
vaccination_doses_df=pd.read_csv("Resources/vaccine_doses.csv")
vaccination_doses_df.tail(1) 


#the last rows basically gives us cumulative data for total_individuals_at_least_one	total_individuals_partially_vaccinated	total_doses_in_fully_vaccinated_individuals	total_individuals_fully_vaccinated	total_individuals_3doses

,report_date,previous_day_total_doses_administered,previous_day_at_least_one,previous_day_fully_vaccinated,previous_day_3doses,total_doses_administered,total_individuals_at_least_one,total_individuals_partially_vaccinated,total_doses_in_fully_vaccinated_individuals,total_individuals_fully_vaccinated,total_individuals_3doses
818,2023-03-30,3654,118,162,197.0,38299648,12692462,462110,NaN,12230352,7705951.0

previous_day_total_doses_administered	Total number of doses administered during the previous day.
previous_day_at_least_one	Number of individuals who received their first dose during the previous day.
previous_day_fully_vaccinated	Number of individuals who became fully vaccinated the previous day.
previous_day_3doses	Number of individuals who became vaccinated with three doses the previous day.
total_doses_administered	Total number of doses administered to date.
total_individuals_at_least_one	Cumulative number of individuals who have received at least one dose.
total_individuals_partially_vaccinated	"Cumulative number of individuals who are partially vaccinated. Partially vaccinated is defined as receiving:
- the first of a two-dose vaccine series (e.g., Pfizer or Moderna), where the vaccine is Health Canada approved, or
- the first of a two-dose vaccine series, where the vaccine(s) is not Health Canada approved, or
- two doses of non-Health Canada approved vaccines, or
- one dose of a Health Canada-approved vaccine, followed by one dose of a non-Health Canada approved vaccine."
total_doses_in_fully_vaccinated_individuals	Total number of doses administered to individuals who had received two doses.  Discontinued as of December 3, 2021.
total_individuals_fully_vaccinated	"Cumulative number of individuals who are fully vaccinated. Fully vaccinated is defined as recieving: 
-one dose of Janssen (Johnson & Johnson), or
-two doses of any Health Canada approved vaccine, or
-one dose of a non-Health Canada approved vaccine, followed by one dose of a Health Canada-approved vaccine, or 
-three doses of any Health Canada approved vaccine, or 
-three doses of a vaccine, whether it is Health Canada approved or not."
total_individuals_3doses	"Cumulative number of individuals who are vaccinated with three doses. Vaccinated with three doses is defined as receiving three doses of any Health Canada approved vaccine. 
These individuals are a subset of the individuals captured in ""total_individuals_fully_vaccinated""."

 # Vaccination data by age: absolute numbers

In [14]:
vaccinesbyage_df=pd.read_csv("Resources/vaccines_by_age.csv")
vaccinesbyage_df.tail(13) 
#All data are cumulative so looking on tail gives us the total numbers

,Date,Agegroup,At least one dose_cumulative,Second_dose_cumulative,fully_vaccinated_cumulative,third_dose_cumulative,Total population,Percent_at_least_one_dose,Percent_fully_vaccinated,Percent_3doses
10142,2023-03-30,05-11yrs,542959,0,421288,78121,1075423,0.5049,0.3917,0.0726
10143,2023-03-30,12-17yrs,803943,0,760615,207031,961857,0.8358,0.7908,0.2152
10144,2023-03-30,18-29yrs,2197149,0,2110712,994302,2454802,0.8950,0.8598,0.4050
10145,2023-03-30,30-39yrs,1899608,0,1839208,1012055,2077137,0.9145,0.8855,0.4872
10146,2023-03-30,40-49yrs,1706895,0,1668234,1034890,1855340,0.9200,0.8992,0.5578
10147,2023-03-30,50-59yrs,1830984,0,1797991,1278854,2019276,0.9068,0.8904,0.6333
10148,2023-03-30,60-69yrs,1782893,0,1753918,1437335,1813493,0.9831,0.9671,0.7926
10149,2023-03-30,70-79yrs,1191271,0,1175811,1053253,1181151,0.9999,0.9955,0.8917
10150,2023-03-30,80+,673407,0,664577,610048,674976,0.9977,0.9846,0.9038
10151,2023-03-30,Adults_18plus,11282207,0,11010451,7420737,12076175,0.9343,0.9117,0.6145
10152,2023-03-30,Ontario_12plus,12086150,0,11771066,7627768,13038032,0.9270,0.9028,0.5850
10153,2023-03-30,Ontario_5plus,12629109,0,12192354,7705889,14113455,0.8948,0.8639,0.5460
10154,2023-03-30,Undisclosed_or_missing,1568,0,431,40,0,0.0000,0.0000,0.0000

In [15]:
vaccinesbyage_df.columns

Index(['Date', 'Agegroup', 'At least one dose_cumulative',
       'Second_dose_cumulative', 'fully_vaccinated_cumulative',
       'third_dose_cumulative', 'Total population',
       'Percent_at_least_one_dose', 'Percent_fully_vaccinated',
       'Percent_3doses'],
      dtype='object')

In [16]:
vaccinesbyage_df["Agegroup"].unique()

array(['12-17yrs', '18-29yrs', '30-39yrs', '40-49yrs', '50-59yrs',
       '60-69yrs', '70-79yrs', '80+', 'Adults_18plus', 'Ontario_12plus',
       'Undisclosed_or_missing', '05-11yrs', 'Ontario_5plus'],
      dtype=object)

In [18]:
vaccinebyage_df= vaccinesbyage_df.tail(13) 
vaccinebyage_df

,Date,Agegroup,At least one dose_cumulative,Second_dose_cumulative,fully_vaccinated_cumulative,third_dose_cumulative,Total population,Percent_at_least_one_dose,Percent_fully_vaccinated,Percent_3doses
10142,2023-03-30,05-11yrs,542959,0,421288,78121,1075423,0.5049,0.3917,0.0726
10143,2023-03-30,12-17yrs,803943,0,760615,207031,961857,0.8358,0.7908,0.2152
10144,2023-03-30,18-29yrs,2197149,0,2110712,994302,2454802,0.8950,0.8598,0.4050
10145,2023-03-30,30-39yrs,1899608,0,1839208,1012055,2077137,0.9145,0.8855,0.4872
10146,2023-03-30,40-49yrs,1706895,0,1668234,1034890,1855340,0.9200,0.8992,0.5578
10147,2023-03-30,50-59yrs,1830984,0,1797991,1278854,2019276,0.9068,0.8904,0.6333
10148,2023-03-30,60-69yrs,1782893,0,1753918,1437335,1813493,0.9831,0.9671,0.7926
10149,2023-03-30,70-79yrs,1191271,0,1175811,1053253,1181151,0.9999,0.9955,0.8917
10150,2023-03-30,80+,673407,0,664577,610048,674976,0.9977,0.9846,0.9038
10151,2023-03-30,Adults_18plus,11282207,0,11010451,7420737,12076175,0.9343,0.9117,0.6145
10152,2023-03-30,Ontario_12plus,12086150,0,11771066,7627768,13038032,0.9270,0.9028,0.5850
10153,2023-03-30,Ontario_5plus,12629109,0,12192354,7705889,14113455,0.8948,0.8639,0.5460
10154,2023-03-30,Undisclosed_or_missing,1568,0,431,40,0,0.0000,0.0000,0.0000

In [19]:
vaccinebyage_df.to_csv("Output/vaccinebyage.csv")